### ISSUE TITLE
Error while creating RabbitMQReceiver

### ISSUE THREAD

**Issue by KevinMellott91** [Stratio/rabbitmq-receiver#10]
I'm attempting to consume messages from an existing RabbitMQ queue, and am getting the following error messages. Does anybody know what this may indicate?

```
15/08/14 12:54:07 ERROR RabbitMQReceiver: Got this unknown exception: java.util.NoSuchElementException: None.get
15/08/14 12:54:07 ERROR ReceiverTracker: Deregistered receiver for stream 0: Restarting receiver with delay 2000ms: Trying to connect again
```

My Spark Streaming app is pretty basic; the code for this is below.

```
def main(args: Array[String]) {
    val conf = new SparkConf()
      .setAppName("streaming-sample-app")
      .setIfMissing("spark.master", "local[*]")
    val ssc = new StreamingContext(conf, Seconds(3))

    val receiverStream = RabbitMQUtils.createStream(ssc, Map(
      "host" -> "dev.company.com",
      "queueName" -> "messaging",
      "vHost" -> "logging",
      "username" -> "username",
      "password" -> "password"
    ))

    receiverStream.start()
    receiverStream.foreachRDD(r => println(r.count()))

    ssc.start()             // Start the computation
    ssc.awaitTermination()  // Wait for the computation to terminate
  }
```

Thanks in advance for any assistance - once I get this working I will submit a pull request with an example usage.

Thanks,
Kevin

**Comment by danielcsant** [comment]
Threre where some bugs retrieving the properties. It is fixed on master branch. 
Looking forward to your PR ;)

**Comment by oscarcastaneda** [comment]
I tested this with master branch and found that it indeed works. I hereby confirm that it is possible to consume messages from an existing RabbitMQ queue.

**Comment by KevinMellott91** [comment]
Thank you both! I'm actively working on a PR with an example and look forward to your feedback on it.
