### ISSUE TITLE
Read from a durable queue

### ISSUE THREAD

**Issue by frankyin1019** [Stratio/rabbitmq-receiver#11]
Hi, I'm using the 0.1.0_RELEASE version. When I try to read from a durable queue, it throws the exception:
ERROR ReceiverTracker: Deregistered receiver for stream 0: Error starting receiver 0 - java.io.IOException

and it is caused by:
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - parameters for queue 'xxxxx' in vhost '/' not equivalent, class-id=50, method-id=10)

In our use case, it is important to keep the queue durable. Is it possible to read from a durable queue with the current release of rabbitmq-receiver?

Thanks

**Comment by danielcsant** [comment]
Hi,

As you say 0.1.0_RELEASE does not work with durable queues. 

Please try master branch and give us feedback if it does not work neither. It should work.

As soon as we close some features a new release will be made

**Comment by frankyin1019** [comment]
thanks a lot the master branch works well.
